# Generated by Django 3.1 on 2020-08-26 19:40

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('name', models.CharField(max_length=100)),
                ('user_type', models.CharField(choices=[('AMB', 'Ambulance'), ('BLB', 'Blood-Bank'), ('HSP', 'Hospital'), ('MST', 'Medical-Store')], max_length=3)),
            ],
            options={
                'unique_together': {('email', 'user_type')},
            },
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
    ]
