# Generated by Django 3.1 on 2020-09-22 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20200920_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='pincode',
        ),
    ]
