# Generated by Django 3.1 on 2020-10-16 17:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('company_contact', models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(1000000000)])),
                ('company_address', models.CharField(max_length=200)),
                ('company_email', models.EmailField(max_length=254)),
                ('gst_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distributor_name', models.CharField(max_length=50)),
                ('bill_number', models.CharField(max_length=10)),
                ('bill_date', models.DateField(null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=4)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='medical_store.companydetails')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(max_length=10)),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_contact', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(1000000000)])),
                ('referred_by', models.CharField(max_length=50)),
                ('bill_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=4)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalesInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('batch_number', models.CharField(max_length=20)),
                ('price_of_each', models.PositiveIntegerField()),
                ('sales_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='salesinventory', to='medical_store.sales')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('batch_number', models.CharField(max_length=20)),
                ('price_of_each', models.PositiveIntegerField()),
                ('mrp', models.PositiveIntegerField()),
                ('mfd', models.DateField()),
                ('expiry', models.DateField()),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchaseinventory', to='medical_store.purchase')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HSNcode', models.CharField(blank=True, default='3004', max_length=6)),
                ('batch_number', models.CharField(max_length=20)),
                ('medicine_name', models.CharField(max_length=200)),
                ('mfd', models.DateField()),
                ('expiry', models.DateField()),
                ('purchase_price', models.PositiveIntegerField()),
                ('sale_price', models.PositiveIntegerField()),
                ('medicine_quantity', models.PositiveIntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('company_name', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.DO_NOTHING, to='medical_store.companydetails')),
            ],
        ),
    ]
