# Generated by Django 3.1.1 on 2020-09-21 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_store', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accounting',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='billing',
        ),
        migrations.DeleteModel(
            name='Billing',
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
        migrations.DeleteModel(
            name='MedicineInventory',
        ),
    ]
