# Generated by Django 3.1 on 2020-10-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='customer_contact',
            field=models.BigIntegerField(),
        ),
    ]
