# Generated by Django 3.1.1 on 2020-10-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineinventory',
            name='isexpired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchaseinventory',
            name='isexpired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesinventory',
            name='isexpired',
            field=models.BooleanField(default=False),
        ),
    ]
