# Generated by Django 3.1 on 2020-10-23 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_store', '0002_auto_20201022_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='company_name',
            field=models.CharField(max_length=200),
        ),
    ]
