# Generated by Django 3.1 on 2020-09-26 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical_store', '0003_companydetails_medicineinventory_purchase_purchaseinventory_sales_salesinventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineinventory',
            name='company_name',
            field=models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.DO_NOTHING, to='medical_store.companydetails'),
        ),
    ]
