# Generated by Django 3.1.1 on 2020-09-26 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_store', '0003_companydetails_medicineinventory_purchase_purchaseinventory_sales_salesinventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companydetails',
            name='account',
        ),
    ]
