# Generated by Django 3.1.1 on 2020-09-26 09:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_store', '0004_remove_companydetails_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='company_contact',
            field=models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(1000000000)]),
        ),
    ]
