# Generated by Django 3.1.1 on 2020-09-29 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_store', '0005_auto_20200926_0941'),
        ('medical_store', '0004_auto_20200926_1214'),
    ]

    operations = [
    ]
