# Generated by Django 3.1.1 on 2020-10-03 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_store', '0006_merge_20200929_1907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseinventory',
            old_name='purchase_id',
            new_name='purchase',
        ),
    ]
