# Generated by Django 3.1.1 on 2020-10-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_store', '0008_auto_20201003_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='bill_date',
            field=models.DateField(null=True),
        ),
    ]
