# Generated by Django 3.1.1 on 2020-10-10 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical_store', '0011_auto_20201010_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinventory',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_store.purchase'),
        ),
    ]
