# Generated by Django 3.1.1 on 2020-10-11 04:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('medical_store', '0013_auto_20201010_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinventory',
            name='expiry',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseinventory',
            name='mfd',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseinventory',
            name='mrp',
            field=models.PositiveIntegerField(default=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaseinventory',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchaseinventory', to='medical_store.purchase'),
        ),
    ]
