# Generated by Django 3.1.1 on 2020-10-11 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_store', '0014_auto_20201011_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineinventory',
            name='expiry',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='medicineinventory',
            name='mfd',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='purchaseinventory',
            name='expiry',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='purchaseinventory',
            name='mfd',
            field=models.DateField(null=True),
        ),
    ]
