# Generated by Django 3.1.1 on 2020-10-11 10:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('medical_store', '0015_auto_20201011_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineinventory',
            name='expiry',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicineinventory',
            name='mfd',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaseinventory',
            name='expiry',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaseinventory',
            name='mfd',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sales',
            name='bill_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='salesinventory',
            name='sales_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='salesinventory', to='medical_store.sales'),
        ),
    ]
