# Generated by Django 3.1.1 on 2020-10-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_store', '0016_auto_20201011_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='bill_number',
            field=models.CharField(default='12AC', max_length=10),
            preserve_default=False,
        ),
    ]
